{{- if and .Values.ingress.enabled .Values.ingress.tlsCertificate.create .Values.ingress.tlsCertificate.certificate .Values.ingress.tlsCertificate.privateKey -}}
apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.ingress.tlsCertificate.secretName | default (printf "%s-tls" (include "semaphoreui.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "semaphoreui.labels" . | nindent 4 }}

type: kubernetes.io/tls

data:
  {{ .Values.ingress.tlsCertificate.certificateKey }}: {{ .Values.ingress.tlsCertificate.certificate | b64enc }}
  {{ .Values.ingress.tlsCertificate.privateKeyKey }}: {{ .Values.ingress.tlsCertificate.privateKey | b64enc }}
{{- end }}